name: CI

on:
  push:
    branches: [ master ]
    
    
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules, !docker-compose.yml"
          target: "~/app/rentx-api"
          
      - name: Update API
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app/rentx-api
            yarn
            ./node_modules/.bin/typeorm migration:run
            pm2 restart rentx_api
